2021-01-04 12:23:00 | Error | AuroraEvent:Disconnected | Exception: Fehler beim Senden der Anforderung. | InnerException: System.Net.Http.HttpRequestException Fehler beim Senden der Anforderung. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
WebException Die Verbindung mit dem Remoteserver kann nicht hergestellt werden. System.Net.WebResponse EndGetResponse(System.IAsyncResult)
SocketException Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat 192.168.0.210:16021 Void InternalEndConnect(System.IAsyncResult)
2021-01-04 12:23:00 | Error | AuroraEvent:Disconnected | Exception: Fehler beim Senden der Anforderung. | InnerException: System.Net.Http.HttpRequestException Fehler beim Senden der Anforderung. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
WebException Die Verbindung mit dem Remoteserver kann nicht hergestellt werden. System.Net.WebResponse EndGetResponse(System.IAsyncResult)
SocketException Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat 192.168.0.210:16021 Void InternalEndConnect(System.IAsyncResult)
2021-01-04 12:23:09 | Error | Call:http://192.168.0.210:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value: Retry:False:ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2021-01-04 12:23:09 | Error | Call:http://192.168.0.210:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value: Retry:False:ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2021-01-04 12:23:21 | Error | Call:http://192.168.0.210:16021/api/v1/ Value: Retry:True:ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2021-01-04 12:23:21 | Error | Call:http://192.168.0.210:16021/api/v1/ Value: Retry:True:ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
